### ISSUE TITLE
Reset button does not remove solute particles that are in mid-air

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/concentration#45] opened 2015-11-09 16:13 UTC
Found in testing for Beers Law Lab, Issue is also present here in concentration.
Reposting issue here.
https://github.com/phetsims/beers-law-lab/issues/122

**Comment by pixelzoom** [comment] 2015-11-09 21:53
Concentration is a subset of Beer's Law, so this is a duplicate of phetsims/beers-law-lab#122 and will be addressed there. Closing.

**Closed by pixelzoom** 2015-11-09 21:53 UTC
