### ISSUE TITLE
Flickering particles when solution from dropper is added to a "Saturated!" beaker.

### ISSUE THREAD

**Issue by learnthinkteach** [phetsims/concentration#1] opened 2013-09-25 21:27 UTC
"Flickering" particles appear and disappear quickly from the bottom of the beaker as solution is added from the dropper to a saturated beaker.  Possibly an issue when the amount of solute in the beaker is borderline for a whole number value of calculated particles?

Noticed for red (cobalt), orange, yellow, and green solutions; have not tried them all, but these examples show that this behavior is happening for low, medium, and high saturation concentration chemicals.  Observed in Chrome and Firefox.  Easiest to observe with yellow solution.

Firefox troubleshooting info:
Name: Concentration
URL: http://www.colorado.edu/physics/phet/dev/html/concentration/1.0.0-rc.1/concentration_en.html
Version: 1.0.0-rc.1
Features missing: flexbox, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:24.0) Gecko/20100101 Firefox/24.0
Language: en-US
Window: 1083x593
Pixel Ratio: 1/1

Chrome troubleshooting info:
Name: Concentration
URL: http://www.colorado.edu/physics/phet/dev/html/concentration/1.0.0-rc.1/concentration_en.html
Version: 1.0.0-rc.1
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.76 Safari/537.36
Language: en-US
Window: 1377x852
Pixel Ratio: 1/1

**Comment by pixelzoom** [comment] 2015-08-30 20:04
I'll investigate resolving this for S2015R.

**Comment by pixelzoom** [comment] 2015-08-31 19:05
Steps to reproduce:

1. select Potassium Chromate from "Solute" combo box
2. select "Solution" (dropper) radio button
3. add and drain solution (or evaporate) under precipitate forms (at around 3.3 mol/L)
4. add solution with dropper
5. watch precipitate particles "flicker" as some are added and immediately removed

**Comment by pixelzoom** [comment] 2015-08-31 20:40
Using the dropper to add solution calls `ConcentrationModel.addStockSolutionFromDropper`, which calls `addSolvent` (which changes `solution.volume`), followed by `addSolute` (which changes solution.soluteAmountProperty`).  The increase of volume removes particle(s), then the change in solute amount adds particle(s).  This is the source of the "flickering".  When adding stock solution, we should only see particles being added, not removed.

**Comment by pixelzoom** [comment] 2015-08-31 21:44
Fixed in https://github.com/phetsims/beers-law-lab/commit/822ec10c8fc057337344ae9b81661b6d1b1f6d16.

**Comment by pixelzoom** [comment] 2015-08-31 22:04
Fixed in this dev version:

http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.0-dev.8/concentration_en.html

Assigning to @ariel-phet to verify (or decide who to assign to verify) since the team lead is no longer with the project.

**Comment by pixelzoom** [comment] 2015-09-01 03:30
Hi @amyh-phet, @ariel-phet tells me you're the new lead on this sim. Could you please review the fix for this issue? Steps to reproduce at in https://github.com/phetsims/concentration/issues/1#issuecomment-136468976. Thanks.

**Comment by amyh-phet** [comment] 2015-09-01 15:29
@pixelzoom    Reviewed fix.   No flickering particles in dev version with any solutes tested.   Closing issue.

**Closed by amyh-phet** 2015-09-01 15:29 UTC
Labels: Summer 2015 redeploy

**Comment by pixelzoom** [comment] 2015-09-01 15:39
Great, thanks.
