### ISSUE TITLE
Volume change bug

### ISSUE THREAD

**Issue by Nanodot** [phetsims/concentration#55] opened 2019-05-13 15:28 UTC
It can be clearly seen in this app that when adding nearly 180g NaCl to 0.5L water (6.150M) the solution level is unchanged. Nor is the final volume shown anywhere in the Sim.

Attached is a file that has room temperature density data for each of your systems. It includes the screenshot as well as typed values.

Perhaps this data will assist in getting the ball rolling on this bug fix.
[PhET Molarity.docx](https://github.com/phetsims/concentration/files/3173620/PhET.Molarity.docx)

**Comment by pixelzoom** [comment] 2019-05-13 16:02
@Nanodot please clarify what you think is incorrect, and what needs to be fixed.

**Comment by arouinfar** [comment] 2019-05-13 16:05
@Nanodot thank you for reaching out to us.

What you've encountered is not a bug; it was a deliberate design decision. In the simulation, concentration is calculated as solute amount divided by **water** volume, and the corresponding simplified equation for concentration is: Moles of Solute / Volume of Solvent. The volume of dissolved solute has only a small effect on solution volume, and different volume changes for each solute could be confusing to students. 

For more information about the model, please see the Teacher Tips document on the Concentration simulation page.
https://phet.colorado.edu/en/simulation/concentration#for-teachers-header

**Comment by Nanodot** [comment] 2019-05-13 19:55
This app is clearly NOT UG-Gen Chem useful at all - IMO. By UG-Intro i assume, in hindsight, this is for non-science majors?

I teach college level Gen Chem (10+ years now) and i am looking for simulators to help my students with concentrations of M, m, and mass%. Clearly this sim is not ever going to help them... Thanks for explaining the underlying simplifying assumptions for your target audience.

BTW, 30% (near satd.) solution of NiCl2 has a density of 1.326 g/mL.  The attached spreadsheet plots show how these solutions should behave in the real world and ~half your chosen chemicals have significant density at saturation:

[PhET concentration Correction Factors.xlsx](https://github.com/phetsims/concentration/files/3174472/PhET.concentration.Correction.Factors.xlsx)

BTW2, i find this statement very disturbing for ALL future PhET UG based applications:
            "... implementation complexity doesn’t align with Html5."  This alone is very discouraging news for my needs.

Thanks for rapid feedback!!
Charles

**Comment by ariel-phet** [comment] 2019-05-14 02:38
@Nanodot we appreciate the feedback, and understand your concerns. We choose each simulation to align with certain learning goals, and as we all know, whenever we are describing science we are using a model. For example, when we write down a chemical equation, there might actually be millions of intermediate products and steps, but we are choosing an overall representation.

So, as to your comment of "implementation complexity does not align with HTML5" - that is not at all the case here. We made a specific pedagogical choice for this simulation. We may consider a more advanced version in the future, but this simulation is widely used in its current form.

Of course, we deeply respect the professionalism of teachers and we know that they know their classrooms best. So indeed, this simulation may well not be a good tool for your particular classroom and needs. So certainly do not hesitate to contact us if you have future concerns about the model in a simulation, but in this particular case, as stated above, a conscious simplification was made.

**Comment by Nanodot** [comment] 2019-05-14 12:59
I understand the philosophy, thanks for explaining. I think as long as your target audience are not going to be science students in college it is a good idea to simplify this way. 

One example of over-simplification we see in Univ Gen Chem are students that MAY have learned in HS that Acid/Base reactions can be calculated using the "dilution equation" i.e. proportionality. That only works when the teacher gives 1:1 ratios - if they get a diprotic acid most will apply the rubric they know. 

I think this topic/thread can be closed now if you like.

**Comment by pixelzoom** [comment] 2019-05-14 15:07
Thank you @Nanodot.  Closing.

**Closed by pixelzoom** 2019-05-14 15:07 UTC
Labels: type:user-feedback
