### ISSUE TITLE
Issue "?stringTest=double" covering objects

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/concentration#42] opened 2015-05-26 17:57 UTC
Testing for task https://github.com/phetsims/tasks/issues/245
Solution, Solute option box covers shaker
Refresh button covers the remove solute button
![screen shot 2015-05-26 at 11 55 51 am](https://cloud.githubusercontent.com/assets/5631059/7819345/571ab32a-039e-11e5-9beb-23a01d445642.png)

**Comment by pixelzoom** [comment] 2015-05-26 18:11
This is a duplicate of https://github.com/phetsims/beers-law-lab/issues/100. As noted in https://github.com/phetsims/tasks/issues/252#issuecomment-104764079, I have already tested all of my sims for this issue.

**Closed by pixelzoom** 2015-05-26 18:11 UTC
