### ISSUE TITLE
CT stateObject provided a public key that is not in the schema: velocity

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/concentration#63] opened 2023-01-26 16:47 UTC
```
concentration : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/concentration/concentration_en.html?continuousTest=%7B%22test%22%3A%5B%22concentration%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674717977207%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioDataHandler.ts:215:54)
at getPhetioData (Emitter.ts:122:17)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM

----------------------------------

concentration : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/concentration/concentration_en.html?continuousTest=%7B%22test%22%3A%5B%22concentration%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674729225424%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioDataHandler.ts:215:54)
at getPhetioData (Emitter.ts:122:17)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM
```

**Comment by pixelzoom** [comment] 2023-01-26 18:10
Concentration is a single screen of Beer's Law Lab, so this is a duplicate of https://github.com/phetsims/beers-law-lab/issues/311.  Closing.

**Closed by pixelzoom** 2023-01-26 18:10 UTC
Labels: type:automated-testing
